"""update api keys constraints

Revision ID: b1bd0269550c
Revises: e14856b62711
Create Date: 2026-02-01 20:45:43.039309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1bd0269550c"
down_revision: Union[str, Sequence[str], None] = "e14856b62711"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.VARCHAR(),
        server_default="default",
        existing_nullable=False,
        schema="auth",
    )
    op.create_index(
        "ix_api_keys_revoked_at", "api_keys", ["revoked_at"], unique=False, schema="auth"
    )
    op.create_index(
        "ix_api_keys_workspace_id", "api_keys", ["workspace_id"], unique=False, schema="auth"
    )
    op.create_unique_constraint("uq_api_keys_key_hash", "api_keys", ["key_hash"], schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_api_keys_key_hash", "api_keys", schema="auth", type_="unique")
    op.drop_index("ix_api_keys_workspace_id", table_name="api_keys", schema="auth")
    op.drop_index("ix_api_keys_revoked_at", table_name="api_keys", schema="auth")
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
        schema="auth",
    )
    # ### end Alembic commands ###
