from dataclasses import dataclass
from datetime import datetime

from billing.domain.credits.entities import CreditGrant
from billing.domain.credits.value_objects import (
    Credits,
    GrantId,
)
from billing.domain.shared.enums import CreditSource
from billing.domain.shared.ids import (
    ReferenceId,
    RequestId,
    UserId,
)
from billing.domain.shared.value_objects import PlanCode
from billing.domain.subscription.entities import (
    Subscription,
)
from billing.domain.subscription.events import (
    SubscriptionCanceled,
    SubscriptionCreated,
    SubscriptionCreditsGranted,
    SubscriptionRenewed,
)
from billing.domain.subscription.exceptions import (
    DuplicatePeriodGrant,
)
from billing.domain.subscription.plans import (
    SubscriptionPlan,
    get_subscription_plan,
)
from billing.domain.subscription.value_objects import (
    SubscriptionId,
)


@dataclass(frozen=True, slots=True)
class CreateSubscriptionResult:
    subscription: Subscription
    event: SubscriptionCreated


def create_subscription(
    *,
    subscription_id: SubscriptionId,
    user_id: UserId,
    plan_code: PlanCode,
    current_period_start: datetime,
    current_period_end: datetime,
    now: datetime,
    provider_subscription_id: str | None = None,
) -> CreateSubscriptionResult:
    plan = get_subscription_plan(plan_code)

    subscription = Subscription(
        subscription_id=subscription_id,  # to be generated by the repository
        user_id=user_id,
        plan_code=plan.code,
        status="active",
        current_period_start=current_period_start,
        current_period_end=current_period_end,
        cancel_at_period_end=False,
        provider_subscription_id=provider_subscription_id,
        last_granted_period_start=None,
    )

    event = SubscriptionCreated(
        subscription_id=subscription_id,
        user_id=user_id,
        plan_code=plan.code,
        occurred_at=now,
        metadata={
            "period_start": current_period_start.isoformat(),
            "period_end": current_period_end.isoformat(),
        },
    )

    return CreateSubscriptionResult(
        subscription=subscription,
        event=event,
    )


@dataclass(frozen=True, slots=True)
class CancelSubscriptionResult:
    subscription: Subscription
    event: SubscriptionCanceled


def cancel_subscription(
    *,
    subscription: Subscription,
    now: datetime,
    immediate: bool = False,
) -> CancelSubscriptionResult:
    if immediate:
        subscription.cancel_immediately()
    else:
        subscription.mark_cancel_at_period_end()

    event = SubscriptionCanceled(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        occurred_at=now,
        immediate=immediate,
        metadata={
            "immediate": str(immediate).lower(),
        },
    )

    return CancelSubscriptionResult(
        subscription=subscription,
        event=event,
    )


@dataclass(frozen=True, slots=True)
class GrantSubscriptionCreditsResult:
    subscription: Subscription
    grant: CreditGrant
    plan: SubscriptionPlan
    event: SubscriptionCreditsGranted


def grant_subscription_credits(
    *,
    grant_id: GrantId,
    subscription: Subscription,
    # grants: list[CreditGrant],
    request_id: RequestId | None = None,
    # used_request_ids: set[str] | None = None,
    now: datetime,
) -> GrantSubscriptionCreditsResult:
    # now = now or utc_now()

    # TODO: Where to assert idempotent?
    # if (
    #     request_id is not None
    #     and used_request_ids is not None
    #     and str(request_id) in used_request_ids
    # ):
    #     raise IdempotencyConflict(
    #         f"Request {request_id} already processed"
    #     )

    # Subscription validation
    subscription.ensure_active()

    if not subscription.can_grant_for_current_period():
        raise DuplicatePeriodGrant(
            f"Credits for period starting at "
            f"{subscription.current_period_start.isoformat()} already granted"
        )

    plan = get_subscription_plan(subscription.plan_code)

    # Grant the credit
    grant = CreditGrant(
        # TODO: generate grant ID in the repository to ensure uniqueness
        grant_id=grant_id,  # to be generated by the repository
        # user_id=subscription.user_id,
        source=CreditSource.SUBSCRIPTION,
        # granted_credits=plan.credits_grant,
        # remaining_credits=plan.credits_grant,
        total_credits=plan.credits_grant,
        # reference_id=str(subscription.subscription_id),
        reference_id=ReferenceId(
            str(subscription.subscription_id)
        ),
        consumed_credits=Credits(0),
        granted_at=now,
        expires_at=subscription.current_period_end,
        # request_id=request_id,
        # plan_code=plan.code,
        metadata={
            "period_start": subscription.current_period_start.isoformat(),
        },
    )

    subscription.mark_granted_for_current_period()
    # grants.append(grant)

    # TODO: Where to Mark request ID as used?
    # if (
    #     request_id is not None
    #     and used_request_ids is not None
    # ):
    #     used_request_ids.add(str(request_id))

    # updated_subscription = Subscription(
    #     subscription_id=subscription.subscription_id,
    #     user_id=subscription.user_id,
    #     plan_code=subscription.plan_code,
    #     status=subscription.status,
    #     current_period_start=subscription.current_period_start,
    #     current_period_end=subscription.current_period_end,
    #     cancel_at_period_end=subscription.cancel_at_period_end,
    #     provider_subscription_id=subscription.provider_subscription_id,
    #     last_granted_period_start=subscription.current_period_start,
    # )

    # TODO: Where to Build the wallet
    # wallet = build_wallet(
    #     user_id=subscription.user_id,
    #     grants=grants,
    #     now=now,
    # )

    event = SubscriptionCreditsGranted(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        credits=plan.credits_grant,
        plan_code=plan.code,
        occurred_at=now,
        request_id=request_id,
        metadata={
            "period_start": subscription.current_period_start.isoformat(),
        },
    )

    return GrantSubscriptionCreditsResult(
        subscription=subscription,
        grant=grant,
        plan=plan,
        # wallet=wallet,
        event=event,
    )


@dataclass(frozen=True, slots=True)
class RenewSubscriptionResult:
    previous_subscription: Subscription
    subscription: Subscription
    event: SubscriptionRenewed


def renew_subscription(
    *,
    subscription: Subscription,
    next_period_start: datetime,
    next_period_end: datetime,
    now: datetime,
) -> RenewSubscriptionResult:
    # validate subscription status
    previous_subscription = Subscription(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        status=subscription.status,
        current_period_start=subscription.current_period_start,
        current_period_end=subscription.current_period_end,
        cancel_at_period_end=subscription.cancel_at_period_end,
        provider_subscription_id=subscription.provider_subscription_id,
        last_granted_period_start=subscription.last_granted_period_start,
    )

    subscription.renew(
        next_period_start=next_period_start,
        next_period_end=next_period_end,
    )

    # if subscription.status not in ("active", "past_due"):
    #     raise InvalidSubscriptionStatus(
    #         f"Cannot renew subscription in status {subscription.status}"
    #     )

    # updated_subscription = Subscription(
    #     subscription_id=subscription.subscription_id,
    #     user_id=subscription.user_id,
    #     plan_code=subscription.plan_code,
    #     status="active",
    #     current_period_start=next_period_start,
    #     current_period_end=next_period_end,
    #     cancel_at_period_end=subscription.cancel_at_period_end,
    #     provider_subscription_id=subscription.provider_subscription_id,
    #     last_granted_period_start=subscription.last_granted_period_start,
    # )

    event = SubscriptionRenewed(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        occurred_at=now,
        metadata={
            "next_period_start": next_period_start.isoformat(),
            "next_period_end": next_period_end.isoformat(),
        },
    )

    return RenewSubscriptionResult(
        previous_subscription=previous_subscription,
        subscription=subscription,
        event=event,
    )
