from dataclasses import dataclass
from datetime import datetime

from billing.domain.credits.models import CreditGrant
from billing.domain.errors import (
    DuplicatePeriodGrant,
    IdempotencyConflict,
    InvalidSubscriptionStatus,
)
from billing.domain.events import BillingEvent
from billing.domain.subscription.models import Subscription
from billing.domain.subscription.plans import (
    SubscriptionPlan,
    get_subscription_plan,
)
from billing.domain.types import (
    PlanCode,
    RequestId,
    UserId,
    utc_now,
)
from billing.domain.wallet.models import Wallet
from billing.domain.wallet.service import build_wallet


@dataclass(frozen=True)
class CreateSubscriptionResult:
    subscription: Subscription
    event: BillingEvent


def create_subscription(
    user_id: UserId,
    plan_code: PlanCode,
    current_period_start: datetime,
    current_period_end: datetime,
    provider_subscription_id: str | None = None,
) -> CreateSubscriptionResult:
    plan = get_subscription_plan(plan_code)

    subscription = Subscription(
        subscription_id=...,  # to be generated by the repository
        user_id=user_id,
        plan_code=plan.code,
        status="active",
        current_period_start=current_period_start,
        current_period_end=current_period_end,
        cancel_at_period_end=False,
        provider_subscription_id=provider_subscription_id,
        last_granted_period_start=None,
    )

    event = BillingEvent(
        event_type="subscription_created",  # to be generated by the repository
        user_id=user_id,
        plan_code=plan.code,
        metadata={
            "period_start": current_period_start.isoformat(),
            "period_end": current_period_end.isoformat(),
        },
    )

    return CreateSubscriptionResult(
        subscription=subscription,
        event=event,
    )


@dataclass(frozen=True)
class CancelSubscriptionResult:
    subscription: Subscription
    event: BillingEvent


def cancel_subscription(
    subscription: Subscription,
    immediate: bool = False,
) -> CancelSubscriptionResult:
    if immediate:
        updated_subscription = Subscription(
            subscription_id=subscription.subscription_id,
            user_id=subscription.user_id,
            plan_code=subscription.plan_code,
            status="canceled",
            current_period_start=subscription.current_period_start,
            current_period_end=subscription.current_period_end,
            cancel_at_period_end=True,
            provider_subscription_id=subscription.provider_subscription_id,
            last_granted_period_start=subscription.last_granted_period_start,
        )
    else:
        updated_subscription = Subscription(
            subscription_id=subscription.subscription_id,
            user_id=subscription.user_id,
            plan_code=subscription.plan_code,
            status=subscription.status,
            current_period_start=subscription.current_period_start,
            current_period_end=subscription.current_period_end,
            cancel_at_period_end=True,
            provider_subscription_id=subscription.provider_subscription_id,
            last_granted_period_start=subscription.last_granted_period_start,
        )

    event = BillingEvent(
        event_type="subscription_canceled",
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        metadata={
            "immediate": str(immediate).lower(),
        },
    )
    return CancelSubscriptionResult(
        subscription=updated_subscription,
        event=event,
    )


@dataclass(frozen=True)
class GrantSubscriptionCreditsResult:
    subscription: Subscription
    grant: CreditGrant
    plan: SubscriptionPlan
    wallet: Wallet
    event: BillingEvent


def grant_subscription_credits(
    subscription: Subscription,
    grants: list[CreditGrant],
    request_id: RequestId | None = None,
    used_request_ids: set[str] | None = None,
    now: datetime | None = None,
) -> GrantSubscriptionCreditsResult:
    now = now or utc_now()

    # Assert idempotent
    if (
        request_id is not None
        and used_request_ids is not None
        and str(request_id) in used_request_ids
    ):
        raise IdempotencyConflict(
            f"Request {request_id} already processed"
        )

    # Subscription validation
    if subscription.status != "active":
        raise InvalidSubscriptionStatus(
            f"Cannot grant credits for subscription in status {subscription.status}"
        )

    if (
        subscription.last_granted_period_start
        == subscription.current_period_start
    ):
        raise DuplicatePeriodGrant(
            f"Credits for period starting at {subscription.current_period_start.isoformat()} already granted"
        )

    plan = get_subscription_plan(subscription.plan_code)

    # Grant the credit
    grant = CreditGrant(
        # TODO: generate grant ID in the repository to ensure uniqueness
        grant_id=...,  # to be generated by the repository
        user_id=subscription.user_id,
        source="subscription",
        granted_credits=plan.credits_grant,
        remaining_credits=plan.credits_grant,
        created_at=now,
        expires_at=subscription.current_period_end,
        request_id=request_id,
        plan_code=plan.code,
        metadata={
            "period_start": subscription.current_period_start.isoformat(),
        },
    )
    grants.append(grant)

    # Mark request ID as used
    if (
        request_id is not None
        and used_request_ids is not None
    ):
        used_request_ids.add(str(request_id))

    updated_subscription = Subscription(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        status=subscription.status,
        current_period_start=subscription.current_period_start,
        current_period_end=subscription.current_period_end,
        cancel_at_period_end=subscription.cancel_at_period_end,
        provider_subscription_id=subscription.provider_subscription_id,
        last_granted_period_start=subscription.current_period_start,
    )

    # Build the wallet
    wallet = build_wallet(
        user_id=subscription.user_id,
        grants=grants,
        now=now,
    )

    event = BillingEvent(
        event_type="subscription_credits_granted",
        user_id=subscription.user_id,
        credits=plan.credits_grant,
        request_id=request_id,
        plan_code=plan.code,
        metadata={
            "period_start": subscription.current_period_start.isoformat(),
        },
    )

    return GrantSubscriptionCreditsResult(
        subscription=updated_subscription,
        grant=grant,
        plan=plan,
        wallet=wallet,
        event=event,
    )


@dataclass(frozen=True)
class RenewSubscriptionResult:
    previous_subscription: Subscription
    subscription: Subscription
    event: BillingEvent


def renew_subscription(
    subscription: Subscription,
    next_period_start: datetime,
    next_period_end: datetime,
) -> RenewSubscriptionResult:
    # validate subscription status
    if subscription.status not in ("active", "past_due"):
        raise InvalidSubscriptionStatus(
            f"Cannot renew subscription in status {subscription.status}"
        )

    updated_subscription = Subscription(
        subscription_id=subscription.subscription_id,
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        status="active",
        current_period_start=next_period_start,
        current_period_end=next_period_end,
        cancel_at_period_end=subscription.cancel_at_period_end,
        provider_subscription_id=subscription.provider_subscription_id,
        last_granted_period_start=subscription.last_granted_period_start,
    )

    event = BillingEvent(
        event_type="subscription_renewed",
        user_id=subscription.user_id,
        plan_code=subscription.plan_code,
        metadata={
            "next_period_start": next_period_start.isoformat(),
            "next_period_end": next_period_end.isoformat(),
        },
    )

    return RenewSubscriptionResult(
        previous_subscription=subscription,
        subscription=updated_subscription,
        event=event,
    )
