"""omit iam prefix in table constraints

Revision ID: 240a126be8fa
Revises: 9fc0627bbd89
Create Date: 2026-08-24 13:51:30.253290

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "240a126be8fa"
down_revision: Union[str, Sequence[str], None] = "9fc0627bbd89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # primary / unique constraints
    rename_constraint("users", "iam_users_pkey", "users_pkey")

    rename_constraint("roles", "iam_roles_pkey", "roles_pkey")
    rename_constraint("roles", "iam_roles_name_key", "roles_name_key")

    rename_constraint("sessions", "iam_sessions_pkey", "sessions_pkey")

    rename_constraint(
        "authentication_attempts",
        "iam_authentication_attempts_pkey",
        "authentication_attempts_pkey",
    )

    rename_constraint(
        "email_verifications",
        "iam_email_verifications_pkey",
        "email_verifications_pkey",
    )

    rename_constraint(
        "credentials",
        "iam_credentials_pkey",
        "credentials_pkey",
    )

    rename_constraint(
        "refresh_tokens",
        "iam_refresh_tokens_pkey",
        "refresh_tokens_pkey",
    )

    rename_constraint(
        "user_roles",
        "iam_user_roles_pkey",
        "user_roles_pkey",
    )

    rename_constraint(
        "role_permissions",
        "iam_role_permissions_pkey",
        "role_permissions_pkey",
    )

    # foreign keys
    rename_constraint(
        "sessions",
        "iam_sessions_user_id_fkey",
        "sessions_user_id_fkey",
    )

    rename_constraint(
        "authentication_attempts",
        "iam_authentication_attempts_user_id_fkey",
        "authentication_attempts_user_id_fkey",
    )

    rename_constraint(
        "email_verifications",
        "iam_email_verifications_user_id_fkey",
        "email_verifications_user_id_fkey",
    )

    rename_constraint(
        "credentials",
        "iam_credentials_user_id_fkey",
        "credentials_user_id_fkey",
    )

    rename_constraint(
        "refresh_tokens",
        "iam_refresh_tokens_session_id_fkey",
        "refresh_tokens_session_id_fkey",
    )

    rename_constraint(
        "user_roles",
        "iam_user_roles_user_id_fkey",
        "user_roles_user_id_fkey",
    )

    rename_constraint(
        "user_roles",
        "iam_user_roles_role_id_fkey",
        "user_roles_role_id_fkey",
    )

    rename_constraint(
        "role_permissions",
        "iam_role_permissions_role_id_fkey",
        "role_permissions_role_id_fkey",
    )

    # normal indexes
    rename_index("ix_iam_iam_users_email", "ix_users_email")
    rename_index("ix_iam_iam_users_id", "ix_users_id")
    rename_index("ix_iam_iam_users_status", "ix_users_status")

    rename_index(
        "ix_iam_iam_sessions_user_id",
        "ix_sessions_user_id",
    )

    rename_index(
        "ix_iam_iam_authentication_attempts_attempted_at",
        "ix_authentication_attempts_attempted_at",
    )
    rename_index(
        "ix_iam_iam_authentication_attempts_email",
        "ix_authentication_attempts_email",
    )
    rename_index(
        "ix_iam_iam_authentication_attempts_user_id",
        "ix_authentication_attempts_user_id",
    )

    rename_index(
        "ix_iam_iam_email_verifications_token_hash",
        "ix_email_verifications_token_hash",
    )
    rename_index(
        "ix_iam_iam_email_verifications_user_id",
        "ix_email_verifications_user_id",
    )

    rename_index(
        "ix_iam_iam_credentials_status",
        "ix_credentials_status",
    )
    rename_index(
        "ix_iam_iam_credentials_type",
        "ix_credentials_type",
    )
    rename_index(
        "ix_iam_iam_credentials_user_id",
        "ix_credentials_user_id",
    )

    rename_index(
        "ix_iam_iam_refresh_tokens_session_id",
        "ix_refresh_tokens_session_id",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rename_index(
        "ix_refresh_tokens_session_id",
        "ix_iam_iam_refresh_tokens_session_id",
    )

    rename_index(
        "ix_credentials_user_id",
        "ix_iam_iam_credentials_user_id",
    )
    rename_index(
        "ix_credentials_type",
        "ix_iam_iam_credentials_type",
    )
    rename_index(
        "ix_credentials_status",
        "ix_iam_iam_credentials_status",
    )

    rename_index(
        "ix_email_verifications_user_id",
        "ix_iam_iam_email_verifications_user_id",
    )
    rename_index(
        "ix_email_verifications_token_hash",
        "ix_iam_iam_email_verifications_token_hash",
    )

    rename_index(
        "ix_authentication_attempts_user_id",
        "ix_iam_iam_authentication_attempts_user_id",
    )
    rename_index(
        "ix_authentication_attempts_email",
        "ix_iam_iam_authentication_attempts_email",
    )
    rename_index(
        "ix_authentication_attempts_attempted_at",
        "ix_iam_iam_authentication_attempts_attempted_at",
    )

    rename_index(
        "ix_sessions_user_id",
        "ix_iam_iam_sessions_user_id",
    )

    rename_index("ix_users_status", "ix_iam_iam_users_status")
    rename_index("ix_users_id", "ix_iam_iam_users_id")
    rename_index("ix_users_email", "ix_iam_iam_users_email")

    # foreign keys
    rename_constraint(
        "role_permissions",
        "role_permissions_role_id_fkey",
        "iam_role_permissions_role_id_fkey",
    )

    rename_constraint(
        "user_roles",
        "user_roles_role_id_fkey",
        "iam_user_roles_role_id_fkey",
    )
    rename_constraint(
        "user_roles",
        "user_roles_user_id_fkey",
        "iam_user_roles_user_id_fkey",
    )

    rename_constraint(
        "refresh_tokens",
        "refresh_tokens_session_id_fkey",
        "iam_refresh_tokens_session_id_fkey",
    )

    rename_constraint(
        "credentials",
        "credentials_user_id_fkey",
        "iam_credentials_user_id_fkey",
    )

    rename_constraint(
        "email_verifications",
        "email_verifications_user_id_fkey",
        "iam_email_verifications_user_id_fkey",
    )

    rename_constraint(
        "authentication_attempts",
        "authentication_attempts_user_id_fkey",
        "iam_authentication_attempts_user_id_fkey",
    )

    rename_constraint(
        "sessions",
        "sessions_user_id_fkey",
        "iam_sessions_user_id_fkey",
    )

    # primary / unique constraints
    rename_constraint(
        "role_permissions",
        "role_permissions_pkey",
        "iam_role_permissions_pkey",
    )
    rename_constraint(
        "user_roles",
        "user_roles_pkey",
        "iam_user_roles_pkey",
    )
    rename_constraint(
        "refresh_tokens",
        "refresh_tokens_pkey",
        "iam_refresh_tokens_pkey",
    )
    rename_constraint(
        "credentials",
        "credentials_pkey",
        "iam_credentials_pkey",
    )
    rename_constraint(
        "email_verifications",
        "email_verifications_pkey",
        "iam_email_verifications_pkey",
    )
    rename_constraint(
        "authentication_attempts",
        "authentication_attempts_pkey",
        "iam_authentication_attempts_pkey",
    )
    rename_constraint(
        "sessions",
        "sessions_pkey",
        "iam_sessions_pkey",
    )
    rename_constraint(
        "roles",
        "roles_name_key",
        "iam_roles_name_key",
    )
    rename_constraint(
        "roles",
        "roles_pkey",
        "iam_roles_pkey",
    )
    rename_constraint(
        "users",
        "users_pkey",
        "iam_users_pkey",
    )
    # ### end Alembic commands ###


def rename_constraint(
    table: str,
    old_name: str,
    new_name: str,
) -> None:
    op.execute(
        sa.text(
            f'ALTER TABLE iam."{table}" RENAME CONSTRAINT "{old_name}" TO "{new_name}"'
        )
    )


def rename_index(old_name: str, new_name: str) -> None:
    op.execute(sa.text(f'ALTER INDEX iam."{old_name}" RENAME TO "{new_name}"'))
