"""init role table

Revision ID: 25bd63fe6f49
Revises: 7fa0df79d808
Create Date: 2026-08-24 13:38:27.010515

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25bd63fe6f49"
down_revision: Union[str, Sequence[str], None] = "7fa0df79d808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iam_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="iam",
    )
    op.create_table(
        "iam_role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["iam.iam_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission"),
        schema="iam",
    )
    op.create_table(
        "iam_user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["iam.iam_roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["iam.iam_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("iam_user_roles", schema="iam")
    op.drop_table("iam_role_permissions", schema="iam")
    op.drop_table("iam_roles", schema="iam")
    # ### end Alembic commands ###
