"""create identity users and verifications

Revision ID: 43d4ac291661
Revises:
Create Date: 2026-08-24 10:59:54.315115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43d4ac291661"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS iam")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iam_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "LOCKED",
                "DISABLED",
                "SUSPENDED",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_users_email"),
        "iam_users",
        ["email"],
        unique=True,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_users_id"), "iam_users", ["id"], unique=True, schema="iam"
    )
    op.create_index(
        op.f("ix_iam_iam_users_status"),
        "iam_users",
        ["status"],
        unique=False,
        schema="iam",
    )
    op.create_table(
        "iam_email_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["iam.iam_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_email_verifications_token_hash"),
        "iam_email_verifications",
        ["token_hash"],
        unique=True,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_email_verifications_user_id"),
        "iam_email_verifications",
        ["user_id"],
        unique=False,
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_iam_iam_email_verifications_user_id"),
        table_name="iam_email_verifications",
        schema="iam",
    )
    op.drop_index(
        op.f("ix_iam_iam_email_verifications_token_hash"),
        table_name="iam_email_verifications",
        schema="iam",
    )
    op.drop_table("iam_email_verifications", schema="iam")
    op.drop_index(op.f("ix_iam_iam_users_status"), table_name="iam_users", schema="iam")
    op.drop_index(op.f("ix_iam_iam_users_id"), table_name="iam_users", schema="iam")
    op.drop_index(op.f("ix_iam_iam_users_email"), table_name="iam_users", schema="iam")
    op.drop_table("iam_users", schema="iam")
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS iam")
