"""init sessions table

Revision ID: 7fa0df79d808
Revises: 93ba9ae084c3
Create Date: 2026-08-24 13:30:26.690589

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fa0df79d808"
down_revision: Union[str, Sequence[str], None] = "93ba9ae084c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iam_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["iam.iam_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_sessions_user_id"),
        "iam_sessions",
        ["user_id"],
        unique=False,
        schema="iam",
    )
    op.create_table(
        "iam_refresh_tokens",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token_hash", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["iam.iam_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_refresh_tokens_session_id"),
        "iam_refresh_tokens",
        ["session_id"],
        unique=False,
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_iam_iam_refresh_tokens_session_id"),
        table_name="iam_refresh_tokens",
        schema="iam",
    )
    op.drop_table("iam_refresh_tokens", schema="iam")
    op.drop_index(
        op.f("ix_iam_iam_sessions_user_id"), table_name="iam_sessions", schema="iam"
    )
    op.drop_table("iam_sessions", schema="iam")
    # ### end Alembic commands ###
