"""init authentication tables

Revision ID: 93ba9ae084c3
Revises: 43d4ac291661
Create Date: 2026-08-24 11:38:24.646154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93ba9ae084c3"
down_revision: Union[str, Sequence[str], None] = "43d4ac291661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iam_authentication_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=1024), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("SUCCESS", "DENIED", "LOCKED_OUT", name="authentication_outcome"),
            nullable=False,
        ),
        sa.Column(
            "denial_reason",
            sa.Enum(
                "INVALID_CREDENTIALS",
                "ACCOUNT_DISABLED",
                "ACCOUNT_LOCKED",
                "EMAIL_NOT_VERIFIED",
                "UNKNOWN_IDENTITY",
                name="authentication_denial_reason",
            ),
            nullable=True,
        ),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["iam.iam_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="iam",
    )
    op.create_index(
        "ix_auth_attempt_email_attempted_at",
        "iam_authentication_attempts",
        ["email", "attempted_at"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        "ix_auth_attempt_user_attempted_at",
        "iam_authentication_attempts",
        ["user_id", "attempted_at"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_authentication_attempts_attempted_at"),
        "iam_authentication_attempts",
        ["attempted_at"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_authentication_attempts_email"),
        "iam_authentication_attempts",
        ["email"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_authentication_attempts_user_id"),
        "iam_authentication_attempts",
        ["user_id"],
        unique=False,
        schema="iam",
    )
    op.create_table(
        "iam_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("PASSWORD", name="credential_type"), nullable=False),
        sa.Column("secret_hash", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", "COMPROMISED", name="credential_status"),
            nullable=False,
        ),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["iam.iam_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "type", name="uq_user_credential_type"),
        schema="iam",
    )
    op.create_index(
        "ix_credential_type_status",
        "iam_credentials",
        ["type", "status"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        "ix_credential_user_type",
        "iam_credentials",
        ["user_id", "type"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_credentials_status"),
        "iam_credentials",
        ["status"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_credentials_type"),
        "iam_credentials",
        ["type"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_iam_iam_credentials_user_id"),
        "iam_credentials",
        ["user_id"],
        unique=False,
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_iam_iam_credentials_user_id"),
        table_name="iam_credentials",
        schema="iam",
    )
    op.drop_index(
        op.f("ix_iam_iam_credentials_type"), table_name="iam_credentials", schema="iam"
    )
    op.drop_index(
        op.f("ix_iam_iam_credentials_status"),
        table_name="iam_credentials",
        schema="iam",
    )
    op.drop_index("ix_credential_user_type", table_name="iam_credentials", schema="iam")
    op.drop_index(
        "ix_credential_type_status", table_name="iam_credentials", schema="iam"
    )
    op.drop_table("iam_credentials", schema="iam")
    op.drop_index(
        op.f("ix_iam_iam_authentication_attempts_user_id"),
        table_name="iam_authentication_attempts",
        schema="iam",
    )
    op.drop_index(
        op.f("ix_iam_iam_authentication_attempts_email"),
        table_name="iam_authentication_attempts",
        schema="iam",
    )
    op.drop_index(
        op.f("ix_iam_iam_authentication_attempts_attempted_at"),
        table_name="iam_authentication_attempts",
        schema="iam",
    )
    op.drop_index(
        "ix_auth_attempt_user_attempted_at",
        table_name="iam_authentication_attempts",
        schema="iam",
    )
    op.drop_index(
        "ix_auth_attempt_email_attempted_at",
        table_name="iam_authentication_attempts",
        schema="iam",
    )
    op.drop_table("iam_authentication_attempts", schema="iam")
    # ### end Alembic commands ###
