"""omit iam prefix in table names

Revision ID: 9fc0627bbd89
Revises: 25bd63fe6f49
Create Date: 2026-08-24 13:42:17.738911

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fc0627bbd89"
down_revision: Union[str, Sequence[str], None] = "25bd63fe6f49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables
    op.rename_table("iam_users", "users", schema="iam")
    op.rename_table("iam_credentials", "credentials", schema="iam")
    op.rename_table("iam_sessions", "sessions", schema="iam")
    op.rename_table("iam_refresh_tokens", "refresh_tokens", schema="iam")
    op.rename_table(
        "iam_email_verifications",
        "email_verifications",
        schema="iam",
    )
    op.rename_table(
        "iam_authentication_attempts",
        "authentication_attempts",
        schema="iam",
    )

    op.rename_table("iam_roles", "roles", schema="iam")
    op.rename_table("iam_role_permissions", "role_permissions", schema="iam")
    op.rename_table("iam_user_roles", "user_roles", schema="iam")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "iam_users", schema="iam")
    op.rename_table("credentials", "iam_credentials", schema="iam")
    op.rename_table("sessions", "iam_sessions", schema="iam")
    op.rename_table("refresh_tokens", "iam_refresh_tokens", schema="iam")
    op.rename_table(
        "email_verifications",
        "iam_email_verifications",
        schema="iam",
    )
    op.rename_table(
        "authentication_attempts",
        "iam_authentication_attempts",
        schema="iam",
    )

    op.rename_table("roles", "iam_roles", schema="iam")
    op.rename_table("role_permissions", "iam_role_permissions", schema="iam")
    op.rename_table("user_roles", "iam_user_roles", schema="iam")
    # ### end Alembic commands ###
