from dataclasses import dataclass
from datetime import datetime

from billing.domain.credits.entities import (
    ConsumptionAllocation,
    CreditConsumption,
    CreditGrant,
)
from billing.domain.credits.events import CreditsConsumed
from billing.domain.credits.exceptions import (
    InsufficientCredits,
    InvalidCreditsAmount,
)
from billing.domain.credits.policies import (
    grant_priority,
)
from billing.domain.credits.value_objects import (
    ConsumptionId,
    Credits,
)
from billing.domain.shared.ids import RequestId, UserId


@dataclass(frozen=True)
class ConsumeCreditsResult:
    # wallet: Wallet
    consumption: CreditConsumption
    # updated_grants: tuple[CreditGrant, ...]
    touched_grants: tuple[CreditGrant, ...]
    # event: BillingEvent
    event: CreditsConsumed


def consume_credits(
    *,
    consumption_id: ConsumptionId,
    user_id: UserId,
    grants: list[CreditGrant],
    cost: Credits,
    now: datetime,
    request_id: RequestId | None = None,
    # used_request_ids: set[str] | None = None,
    # now: datetime | None = None,
    metadata: dict[str, str] | None = None,
) -> ConsumeCreditsResult:
    # now = now or utc_now()
    if int(cost) < 0:
        raise InvalidCreditsAmount(
            f"cost must be >= 0, got {cost}"
        )

    clean_metadata = dict(metadata or {})

    # validate cost

    # TODO: where to assert idempotency?
    # if (
    #     request_id is not None
    #     and used_request_ids is not None
    #     and str(request_id) in used_request_ids
    # ):
    #     raise IdempotencyConflict(
    #         f"Request {request_id} already processed"
    #     )

    # validate the cost against the wallet balance
    active_grants = [
        g
        for g in grants
        if g.user_id == user_id and g.is_active(now)
    ]
    active_grants.sort(key=grant_priority)

    available = sum(
        int(g.remaining_credits) for g in active_grants
    )

    if available < int(cost):
        raise InsufficientCredits(
            f"Insufficient credits: available {available}, cost {int(cost)}"
        )

    remaining_to_consume = int(cost)
    allocations: list[ConsumptionAllocation] = []
    # updated_by_id: dict[GrantId, CreditGrant] = {}

    touched_grants: list[CreditGrant] = []
    for grant in active_grants:
        if remaining_to_consume == 0:
            break

        to_consume = min(
            int(grant.remaining_credits),
            remaining_to_consume,
        )

        # remaining_to_consume -= to_consume
        if to_consume <= 0:
            continue

        # updated_grant = CreditGrant(
        #     grant_id=grant.grant_id,
        #     user_id=grant.user_id,
        #     source=grant.source,
        #     granted_credits=grant.granted_credits,
        #     remaining_credits=Credits(
        #         int(grant.remaining_credits) - to_consume
        #     ),
        #     created_at=grant.created_at,
        #     expires_at=grant.expires_at,
        #     request_id=grant.request_id,
        #     plan_code=grant.plan_code,
        #     metadata=grant.metadata,
        # )
        # updated_by_id[grant.grant_id] = updated_grant
        # allocations.append(
        #     ConsumptionAllocation(
        #         grant_id=grant.grant_id,
        #         credits=Credits(to_consume),
        #     )
        # )
        # for idx, grant in enumerate(grants):
        #     replacement = updated_by_id.get(grant.grant_id)
        #     if replacement is not None:
        #         grants[idx] = replacement
        allocation = grant.consume(Credits(to_consume))
        allocations.append(allocation)

        touched_grants.append(grant)
        remaining_to_consume -= to_consume

    # TODO: mark request ID as used? where to store used request IDs? should it be stored in a separate table or as part of the wallet/grant state?
    # if (
    #     request_id is not None
    #     and used_request_ids is not None
    # ):
    #     used_request_ids.add(str(request_id))

    consumption = CreditConsumption(
        # TODO: decide on consumption ID generation strategy - should it be generated here or by repository?
        consumption_id=consumption_id,  # to be generated by repository
        user_id=user_id,
        cost=cost,
        created_at=now,
        allocations=tuple(allocations),
        request_id=request_id,
        metadata=clean_metadata,
    )

    # TODO: decide where to build the wallet - should it be built here or by repository? if built here, should it reflect the updated state of the grants after consumption?
    # wallet = build_wallet(
    #     user_id=user_id,
    #     grants=grants,
    #     now=now,
    # )

    # event = BillingEvent(
    #     event_type="credits_charged",
    #     user_id=user_id,
    #     credits=cost,
    #     request_id=request_id,
    #     metadata=metadata,
    # )
    event = CreditsConsumed(
        consumption_id=consumption_id,
        user_id=user_id,
        cost=cost,
        allocations=tuple(allocations),
        occurred_at=now,
        request_id=request_id,
        metadata=clean_metadata,
    )

    return ConsumeCreditsResult(
        # wallet=wallet,
        consumption=consumption,
        # updated_grants=tuple(updated_by_id.values()),
        touched_grants=tuple(touched_grants),
        event=event,
    )
