from dataclasses import dataclass
from datetime import datetime

from billing.domain.credits.models import (
    ConsumptionAllocation,
    CreditConsumption,
    CreditGrant,
)
from billing.domain.credits.policies import grant_priority
from billing.domain.errors import (
    IdempotencyConflict,
    InvalidCreditsAmount,
)
from billing.domain.events import BillingEvent
from billing.domain.types import (
    Credits,
    GrantId,
    RequestId,
    UserId,
    utc_now,
)
from billing.domain.wallet.models import Wallet
from billing.domain.wallet.service import build_wallet


@dataclass(frozen=True)
class ConsumeCreditsResult:
    wallet: Wallet
    consumption: CreditConsumption
    updated_grants: tuple[CreditGrant, ...]
    event: BillingEvent


def consume_credits(
    user_id: UserId,
    grants: list[CreditGrant],
    cost: Credits,
    request_id: RequestId | None = None,
    used_request_ids: set[str] | None = None,
    now: datetime | None = None,
    metadata: dict[str, str] | None = None,
) -> ConsumeCreditsResult:
    now = now or utc_now()
    metadata = metadata or {}

    # validate cost
    if int(cost) < 0:
        raise InvalidCreditsAmount(
            f"cost must be >= 0, got {cost}"
        )

    # assert idempotency
    if (
        request_id is not None
        and used_request_ids is not None
        and str(request_id) in used_request_ids
    ):
        raise IdempotencyConflict(
            f"Request {request_id} already processed"
        )

    # validate the cost against the wallet balance
    active_user_grants = [
        grant
        for grant in grants
        if grant.user_id == user_id
        # and is_grant_active(grant, now)
    ]
    active_user_grants.sort(key=grant_priority)

    available = sum(
        int(grant.remaining_credits)
        for grant in active_user_grants
    )
    if available < int(cost):
        raise InvalidCreditsAmount(
            f"Insufficient credits: available {available}, cost {cost}"
        )

    remaining_to_consume = int(cost)
    allocations: list[ConsumptionAllocation] = []
    updated_by_id: dict[GrantId, CreditGrant] = {}

    for grant in active_user_grants:
        if remaining_to_consume <= 0:
            break

        to_consume = min(
            int(grant.remaining_credits),
            remaining_to_consume,
        )
        # remaining_to_consume -= to_consume
        if to_consume <= 0:
            continue

        updated_grant = CreditGrant(
            grant_id=grant.grant_id,
            user_id=grant.user_id,
            source=grant.source,
            granted_credits=grant.granted_credits,
            remaining_credits=Credits(
                int(grant.remaining_credits) - to_consume
            ),
            created_at=grant.created_at,
            expires_at=grant.expires_at,
            request_id=grant.request_id,
            plan_code=grant.plan_code,
            metadata=grant.metadata,
        )
        updated_by_id[grant.grant_id] = updated_grant
        allocations.append(
            ConsumptionAllocation(
                grant_id=grant.grant_id,
                credits=Credits(to_consume),
            )
        )

    for idx, grant in enumerate(grants):
        replacement = updated_by_id.get(grant.grant_id)
        if replacement is not None:
            grants[idx] = replacement

    # mark request ID as used
    if (
        request_id is not None
        and used_request_ids is not None
    ):
        used_request_ids.add(str(request_id))

    consumption = CreditConsumption(
        # TODO: decide on consumption ID generation strategy - should it be generated here or by repository?
        consumption_id=...,  # to be generated by repository
        user_id=user_id,
        cost=cost,
        created_at=now,
        request_id=request_id,
        allocations=tuple(allocations),
        metadata=metadata,
    )

    wallet = build_wallet(
        user_id=user_id,
        grants=grants,
        now=now,
    )

    event = BillingEvent(
        event_type="credits_charged",
        user_id=user_id,
        credits=cost,
        request_id=request_id,
        metadata=metadata,
    )

    return ConsumeCreditsResult(
        wallet=wallet,
        consumption=consumption,
        updated_grants=tuple(updated_by_id.values()),
        event=event,
    )
